# Generated by Django 4.1 on 2022-08-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gql.chef')),
            ],
            options={
                'verbose_name_plural': 'specialties',
            },
        ),
        migrations.AddField(
            model_name='chef',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql.restaurant'),
        ),
    ]
